server:
  servlet:
    context-path: /maoyan
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maoyan
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: com/cyz/maoyan/mapper/*.xml

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true

alipay:
  easy:
    protocol: https
    gatewayHost: openapi-sandbox.dl.alipaydev.com
    signType: RSA2
    appId: 9021000151606875
    merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCERD5m/IveNfZj2Hod6zeg1A7LLg4iZRxXkd52BG4N+FYiOKLLHLtlFKJIPqCRFGXIcNo11kLp6GBuEachwxSu/FIpOarZWCAHjOhhyaOxaS/ajzTu6oNIEpBmuuBAGEWIr+lj8Wg8XvGjm1ktXtXgSra57SGc+g3Kqz9DXgZ0NciPjYgDYNNSuAEcqfDakzvKldsl3TD0R76hL9hMLJLw5Q6PcmXrrxsHFcokyXp9W0LG8rgWN45GT3F/ibHapx+p0liXy/YdXf2JSdy+scC3j6bLYvQC+U07QXPVQzpyCHihY5Jld3aeHsXTF/y97aVOpg73+29RWzhm2Plt0QnlAgMBAAECggEAKOFu6CXmlSfYn8Oo+tZYuzzP1bzGYZsex3IucAuueGLpPGqE5oJa6UMXZXz14+GKFAnNaBZxWBqas2qBXc4N9ofGXTeVttemDq9eo9rO3WbFg6f/lFinev9B4n6gES9vTnAQkvNqZD50MT0ysvM857YwBAdm/D3NRXbodsn49LG5J64zh+pVj9Z3mveOR717FIxOPVPPt3Sg/fncVIrPwLfZ90soztAHSNrX2IZHUPoBfFp4/44qSspU5VqStj5gfGbNF6eSDVFd3YgipZU/iUaFGjDYgStnioNjcomqmX93dd4OV02bv/RHKt7AYgNAiy2PpeoRjKB/0Cld7eO5gQKBgQC7JB0jDP5mtvg2x2njHIBSURu7cC+iLbPtg9xnhTBrLI5MOB1Kz4FR0q1Bt1he5ygqIwkgO0j5iVX7Ud54WK6ZhGxDMQtfLHyBWDeDXBEjSBh1FQFd8x6K8U7uyHVGFwlfCbTx9Wh3pEc0xrnw4TOtdBxSAnIUwpBOCcC1SiqVxwKBgQC07zAmzl+gCzfPXsPHYbd6B72gmVentSHdaqLHi9lSFe+yyBoPDbXMICkHk3s4aUq5UXYQC19Kac6YwrSgbFIEy+3ZkPSjNs2G7D5t1mUZnK86MkMEpXEYJ27n20yTQPx1iArINKjXK8m55+T7RW0Ybflsox0TfzJKZ+XwiLwy8wKBgQCxKIHwwYdAA2w8p1DFMCEGTEQdkBl3xR409gQ7d6mbe8WFwAVy4beBlxhvQrsEtH2gTiSAf78Yg3uC/EDH2uQG7oZyoUYrpfiDldiPoSOUK9cDV4xAvTunusLHZ7slS/+SGaVS/MgVos3J12sE7pw2UtnQhQIsRvfG+JKWzIw91wKBgGx+aL88TLbpQyQDzR3HiH+SGLEughM8V/wvL0C8qSnBoaPwvT99lx+5wSCb3O1spbQOFt90EkXKwGl1h14S1fOuXQdzFl6wQ/m9u4mdX65F+ATLksg8dF5pduVs6LP76eaIFv8KJJwx05q4ZOQPM2XMvB3aiVrhkMRxHL5pH4DlAoGAXyy9W+xQmVunFjyxbaDjMByDyZmuMATYH9Gqvh1cP7kGK69+WQI1kpFkXojfZiDfwdhJ2LK9YR9JvWfmueTp3L6nd5b8DBsLaIaaTcbip9UkmTeWDJk8PfOyB6f5gnxIToQjIbh/+ZtdESiU8cBwV9iC9Kw5zy0nK365webvKdY=
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnLl0icObIrmUw0F7A/DcZum6JCg3a96214YoyOszlkH8f/fg58xddjxU9hCH4B3NaRekUUh1QgVBa0NIIxkfKLLZo8VOxNoe/rcCezDQOPb98whd46C6gdMcFt9pSAe5sXiAwE/18f2dLm21pHZLjbq4covuDKPGbEWNa4CWxg5tPw2AZGVzDk0+YGh/TIHDuRaluOeKU8qQG0eiOKT1a2TH9aYxKC2iljlHQTzBTD7DI7J3Y2rbLjoxyol8XvXF5nHGwaoGFePE6e/TcTlH9nrwC3uMFYkkhSrVTrc34RBEoWNErJ6sKfEaYCveFvAhXhhTb136UCFfAUaJl5vJ6QIDAQAB
    notifyUrl: https://2affa8a9.r24.cpolar.top/maoyan/alipay/notify
