server:
  servlet:
    context-path: /maoyan
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maoyan
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: com/cyz/maoyan/mapper/*.xml

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
